### PR TITLE
Update kunit result parsing

### PR DESCRIPTION
**Pull request by cbrune**
3 commits here:

- import the unmodified kunit scripts from our enf/impish-19.19 kernel
  tree.
  
- minor tweak to kunit.py to run without a complete kernel tree

- munge the test result to contain the number of test suites

Fixes: SF-73

### CODE REVIEW

**Comment by cbrune** [comment]
To try it out, you can clone my branch and point bazel at the local enkit repo.  You can run the enf_ib_test in the internal tree like this:

```
enfabrica:~/src/internal$ bazel test --override_repository=enkit=/home/curt/src/enkit --test_output=all --cache_test_results=no //driver/ib:enf_ib_unit_test
```

**Comment by ccontavalli** [comment]
Would probably be good to stop vendoring the file, and import it from http_archive + a patch on top? Hard to review the code as is, understand what is ours vs what is upstream. But that's for another day, the PR looks good, approving.

**Comment by cbrune** [comment]
You said the words "approve", but I don't think you clicked the button.

**Comment by cbrune** [comment]
> Would probably be good to stop vendoring the file, and import it from http_archive + a patch on top? Hard to review the code as is, understand what is ours vs what is upstream. But that's for another day, the PR looks good, approving.

Did you read the individual commits?  I think it is pretty clear.

**Review by ccontavalli — APPROVED** [review]

**Comment by rajachan** [comment]
The previous comment is making my head hurt. Did Github switch usernames for who added that comment? Sounds like things Carlo would say but Curt shows as the commenter.

**Review by rajachan — APPROVED** [review]
Now I am all the more confused how the IB test and enf_queues_test in driver/core were reporting data ever

**Comment by cbrune** [comment]
> The previous comment is making my head hurt. Did Github switch usernames for who added that comment? Sounds like things Carlo would say but Curt shows as the commenter.

I know. What the heck happened?  I didn't write that.

**Comment by cbrune** [comment]
> > Did you read the individual commits?  I think it is pretty clear.
> 
> I did, but eg, the first commit is a bunch of diffs on top of what we have in the repository. I have no evidence that you're not undoing modifications that were done manually on the checked in file, or that you did not accidentally slip in a change in that diff
> 
> (I'm not criticizing your work here - the commit train is clean and well formed, thank you! I'm just pointing out that by the choice we made a long time ago to vendor the file, it is now harder to make sure / prove correctness - with the time, I'd go to an http_archive + local patch)
> 
> Give me a second to approve :) got interrupted before clicking the buttons.

OK -- I get it, totally makes sense.  Also this repo is "squash and merge" only, so my commits end up not being helpful to anyone in the future, only at review time.

**Pull request merged**
