### PR TITLE
Copybara update from github.com/buildbuddy-io/buildbuddy to //third_party/buildbuddy

### PR DESCRIPTION
**Pull request by minor-fixes**
See //third_party/buildbuddy/README.md for more details.

The proto files changed in this PR are done automatically via Copybara.
BUILD files are updated manually to get this PR to build correctly.

GitOrigin-RevId: aedaeafdc7b6bc9faaf77494a4598d750bafdf8c
Jira: INFRA-9988

### CODE REVIEW

**Review by monte-enf — APPROVED** [review]
LGTM

**Review by monte-enf — APPROVED** [review]
LGTM - with approval this time.

**Review by monte-enf — APPROVED** [review]
LGTM V3

**Review by mhallmark — APPROVED** [review]

**Pull request merged**
