### PR TITLE
add faketree command, to provide a fake directory tree.

### PR DESCRIPTION
**Pull request by ccontavalli**
See README.md for details, faketree_test.sh, but also the
help message in faketree.go.

### CODE REVIEW

**Review by ahungrynacho — COMMENTED** [review]
I will need to test this against the `//fpga:simlib` build target in the internal repo and grep search for any `~/.cache/bazel...` directories when running locally.

**Review by ahungrynacho — COMMENTED** [review]
Can you make the package downloads less verbose? Every time I build faketree, a ton of `go get` actions are printed to stdout which may drown out some other useful debug information that I purposely `print()` in the bazel rule definitions.

**Review by ahungrynacho — APPROVED** [review]
<removed comment>

**Review by minor-fixes — APPROVED** [review]

**Pull request merged**
