### PR TITLE
New Kernel Artifact Builder

### PR DESCRIPTION
**Pull request by cbrune**
This is a new take on building kernel artifacts for astore and bazel
builds.

Today it generates an archive that is compatible with the bazel
kernel_tree_version() command.

The archive is also able to be used as an APT repository of kernel
.deb packages.  This can be used to install .debs on a VM or real
hardware.

This PR contains a set of helper scripts for building and publishing
kernel artifacts to astore.

This is not a complete solution, but could be used as part of a
larger, automated pipeline for generating kernel artifacts.

See the script `sample-runner.sh` for an example of how to run the
scripts in sequence.

See the README for more.

### CODE REVIEW

**Comment by cbrune** [comment]
The top 3 commits in this internal branch show how the archives are used to build kernel modules:
https://github.com/cbrune/internal/tree/curt/kernel-artifacts

**Comment by cbrune** [comment]
I'll be adding commits to that branch to show how packer can use the new repo also.

**Comment by cbrune** [comment]
> I'll be adding commits to that branch to show how packer can use the new repo also.

@ccontavalli @rajachan 
I pushed new commits to https://github.com/cbrune/internal/tree/curt/kernel-artifacts that show how use the Deb repo from packer and build a VM.

**Review by rajachan — APPROVED** [review]
I'd reviewed this earlier, but forgot to click the green button.

**Pull request merged**
