### PR TITLE
relay server: Add specification and start of documentation

### PR DESCRIPTION
**Pull request by aaahrens**
This PR sketches the proto layout for negotiating new sessions for the relay server. I also has a rough document of the internals. It does not include auth or other non-session based security measures.

### CODE REVIEW

**Review by jacob-adelmann — COMMENTED** [review]
Neat concept! Any speculation on the feature sets we'll create beyond existing TCP-over-WSS implementations?

https://github.com/derhuerst/tcp-over-websockets
https://github.com/jpillora/chisel
https://github.com/MDSLab/wstun

**Comment by aaahrens** [comment]
Re: Auth is not in this draft. Auth is going to be handled after getting the session negotiation correct. 
Reason being is that auth itself is orthogonal to the application, and would probably just be a http/grpc middleware.

**Comment by aaahrens** [comment]
And nothing yet for additional features, but UDP is doable with a couple of patches.

**Review by minor-fixes — COMMENTED** [review]
Please clean up the PR title and first comment (which should become the final squash message)

See https://docs.google.com/document/d/1sfooxl0GcaAqgl79_52pLscSVwJw5RWFUvgacRUyRwI/edit#bookmark=id.x54b1cg57puz

Possible title: `relay server: Add specification and start of documentation`

First comment should contain the [PR description](https://docs.google.com/document/d/1sfooxl0GcaAqgl79_52pLscSVwJw5RWFUvgacRUyRwI/edit#bookmark=id.f3g784hpwsh5)

**Pull request closed without merging**
